### ISSUE TITLE
No Firewatcher needed with Seasonal Weather?

### ISSUE THREAD

**Issue by japinard** [AaronCRobinson/NoFirewatcher#1]
Hi there.  I LOVE your two mods.  Seasonal weather and no firewatcher.  When I went to play today I was very confused because everything was "boring".  Took me a bit to realize I didn't have any weather going on.  So I went to see what happened and you were gone from Steam!  Bummer.  Never used github before but now I'm up and running again with your mods.  But I cannot remember if no firewatcher went before or after seasonal weather -0 or if it's even needed with 1.0?

**Comment by AaronCRobinson** [comment]
The order of the mods should not matter. It is needed for 1.0 and 1.1. Firewatcher will likely always be part of the core game.
